---
abstract: 'Amazon Glacier TreeHash algorithm'
author:
  - 'Victor Efimov'
build_requires: {}
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.131560'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Amazon-TreeHash
provides:
  Net::Amazon::TreeHash:
    file: lib/Net/Amazon/TreeHash.pm
    version: 0.71
requires:
  Digest::SHA: 0
resources:
  license: http://www.gnu.org/licenses/gpl-3.0.txt
version: 0.71
